name: Publish to PYPI

on:
  push:
    branches:
      - release
  pull_request:
    types: [ready_for_review]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release-build:
    name: Create build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: build release distributions
        run: |
          pip install poetry
          poetry build

      - name: upload dists
        uses: actions/upload-artifact@v3
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    name: Release
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v3
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1